# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'realmain.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1911, 1235)
        MainWindow.setMinimumSize(QtCore.QSize(1413, 823))
        MainWindow.setIconSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.subwaymap = QtWidgets.QLabel(self.centralwidget)
        self.subwaymap.setGeometry(QtCore.QRect(0, 10, 1901, 1201))
        self.subwaymap.setText("")
        self.subwaymap.setPixmap(QtGui.QPixmap(":/map_pic/웹 1920 – 1.png"))
        self.subwaymap.setObjectName("subwaymap")
        self.Daehwa = QtWidgets.QLabel(self.centralwidget)
        self.Daehwa.setEnabled(True)
        self.Daehwa.setGeometry(QtCore.QRect(200, 240, 16, 16))
        self.Daehwa.setObjectName("Daehwa")
        self.Juyeop = QtWidgets.QLabel(self.centralwidget)
        self.Juyeop.setEnabled(True)
        self.Juyeop.setGeometry(QtCore.QRect(240, 240, 16, 16))
        self.Juyeop.setText("")
        self.Juyeop.setObjectName("Juyeop")
        self.Jeongbalsan = QtWidgets.QLabel(self.centralwidget)
        self.Jeongbalsan.setEnabled(True)
        self.Jeongbalsan.setGeometry(QtCore.QRect(280, 240, 16, 16))
        self.Jeongbalsan.setText("")
        self.Jeongbalsan.setObjectName("Jeongbalsan")
        self.Daegok = QtWidgets.QLabel(self.centralwidget)
        self.Daegok.setEnabled(True)
        self.Daegok.setGeometry(QtCore.QRect(400, 240, 16, 16))
        self.Daegok.setText("")
        self.Daegok.setObjectName("Daegok")
        self.Baekseok = QtWidgets.QLabel(self.centralwidget)
        self.Baekseok.setEnabled(True)
        self.Baekseok.setGeometry(QtCore.QRect(360, 240, 16, 16))
        self.Baekseok.setText("")
        self.Baekseok.setObjectName("Baekseok")
        self.Madu = QtWidgets.QLabel(self.centralwidget)
        self.Madu.setEnabled(True)
        self.Madu.setGeometry(QtCore.QRect(320, 240, 16, 16))
        self.Madu.setText("")
        self.Madu.setObjectName("Madu")
        self.Hwajeong = QtWidgets.QLabel(self.centralwidget)
        self.Hwajeong.setEnabled(True)
        self.Hwajeong.setGeometry(QtCore.QRect(430, 240, 16, 16))
        self.Hwajeong.setText("")
        self.Hwajeong.setObjectName("Hwajeong")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 111, 16))
        self.label.setObjectName("label")
        self.people_number_lbl = QtWidgets.QLineEdit(self.centralwidget)
        self.people_number_lbl.setGeometry(QtCore.QRect(90, 40, 113, 21))
        self.people_number_lbl.setObjectName("people_number_lbl")
        self.people_group_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.people_group_1.setGeometry(QtCore.QRect(220, 10, 141, 71))
        self.people_group_1.setObjectName("people_group_1")
        self.p_start_lbl_2 = QtWidgets.QLineEdit(self.people_group_1)
        self.p_start_lbl_2.setGeometry(QtCore.QRect(10, 30, 113, 21))
        self.p_start_lbl_2.setObjectName("p_start_lbl_2")
        self.people_group_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.people_group_2.setGeometry(QtCore.QRect(380, 10, 141, 71))
        self.people_group_2.setObjectName("people_group_2")
        self.p_start_lbl_3 = QtWidgets.QLineEdit(self.people_group_2)
        self.p_start_lbl_3.setGeometry(QtCore.QRect(10, 30, 113, 21))
        self.p_start_lbl_3.setObjectName("p_start_lbl_3")
        self.people_group_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.people_group_3.setGeometry(QtCore.QRect(540, 10, 141, 71))
        self.people_group_3.setObjectName("people_group_3")
        self.p_start_lbl_4 = QtWidgets.QLineEdit(self.people_group_3)
        self.p_start_lbl_4.setGeometry(QtCore.QRect(10, 30, 113, 21))
        self.p_start_lbl_4.setObjectName("p_start_lbl_4")
        self.people_group_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.people_group_4.setGeometry(QtCore.QRect(700, 10, 141, 71))
        self.people_group_4.setObjectName("people_group_4")
        self.p_start_lbl_5 = QtWidgets.QLineEdit(self.people_group_4)
        self.p_start_lbl_5.setGeometry(QtCore.QRect(10, 30, 113, 21))
        self.p_start_lbl_5.setObjectName("p_start_lbl_5")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(860, 30, 93, 28))
        self.run_button.setObjectName("run_button")
        self.result_consol = QtWidgets.QTextBrowser(self.centralwidget)
        self.result_consol.setGeometry(QtCore.QRect(1700, 10, 181, 192))
        self.result_consol.setObjectName("result_consol")
        self.Wondang = QtWidgets.QLabel(self.centralwidget)
        self.Wondang.setEnabled(True)
        self.Wondang.setGeometry(QtCore.QRect(455, 240, 16, 16))
        self.Wondang.setText("")
        self.Wondang.setObjectName("Wondang")
        self.Wondang_2 = QtWidgets.QLabel(self.centralwidget)
        self.Wondang_2.setEnabled(True)
        self.Wondang_2.setGeometry(QtCore.QRect(490, 230, 16, 16))
        self.Wondang_2.setText("")
        self.Wondang_2.setObjectName("Wondang_2")
        self.Wondang_3 = QtWidgets.QLabel(self.centralwidget)
        self.Wondang_3.setEnabled(True)
        self.Wondang_3.setGeometry(QtCore.QRect(480, 230, 16, 16))
        self.Wondang_3.setText("")
        self.Wondang_3.setObjectName("Wondang_3")
        self.Wondang_4 = QtWidgets.QLabel(self.centralwidget)
        self.Wondang_4.setEnabled(True)
        self.Wondang_4.setGeometry(QtCore.QRect(480, 240, 16, 16))
        self.Wondang_4.setText("")
        self.Wondang_4.setObjectName("Wondang_4")
        self.Wondang_5 = QtWidgets.QLabel(self.centralwidget)
        self.Wondang_5.setEnabled(True)
        self.Wondang_5.setGeometry(QtCore.QRect(480, 230, 16, 16))
        self.Wondang_5.setText("")
        self.Wondang_5.setObjectName("Wondang_5")
        self.Wonheung = QtWidgets.QLabel(self.centralwidget)
        self.Wonheung.setEnabled(True)
        self.Wonheung.setGeometry(QtCore.QRect(480, 240, 16, 16))
        self.Wonheung.setText("")
        self.Wonheung.setObjectName("Wonheung")
        self.Samsong = QtWidgets.QLabel(self.centralwidget)
        self.Samsong.setEnabled(True)
        self.Samsong.setGeometry(QtCore.QRect(510, 240, 16, 16))
        self.Samsong.setText("")
        self.Samsong.setObjectName("Samsong")
        self.Jichuk = QtWidgets.QLabel(self.centralwidget)
        self.Jichuk.setEnabled(True)
        self.Jichuk.setGeometry(QtCore.QRect(540, 240, 16, 16))
        self.Jichuk.setText("")
        self.Jichuk.setObjectName("Jichuk")
        self.Gupabal = QtWidgets.QLabel(self.centralwidget)
        self.Gupabal.setEnabled(True)
        self.Gupabal.setGeometry(QtCore.QRect(560, 235, 20, 21))
        self.Gupabal.setText("")
        self.Gupabal.setObjectName("Gupabal")
        self.Yeonsinnae = QtWidgets.QLabel(self.centralwidget)
        self.Yeonsinnae.setEnabled(True)
        self.Yeonsinnae.setGeometry(QtCore.QRect(590, 230, 21, 31))
        self.Yeonsinnae.setText("")
        self.Yeonsinnae.setObjectName("Yeonsinnae")
        self.Bulgwang = QtWidgets.QLabel(self.centralwidget)
        self.Bulgwang.setEnabled(True)
        self.Bulgwang.setGeometry(QtCore.QRect(660, 230, 21, 31))
        self.Bulgwang.setText("")
        self.Bulgwang.setObjectName("Bulgwang")
        self.Chungjeongno = QtWidgets.QLabel(self.centralwidget)
        self.Chungjeongno.setEnabled(True)
        self.Chungjeongno.setGeometry(QtCore.QRect(760, 420, 21, 31))
        self.Chungjeongno.setText("")
        self.Chungjeongno.setObjectName("Chungjeongno")
        self.Dongjak = QtWidgets.QLabel(self.centralwidget)
        self.Dongjak.setEnabled(True)
        self.Dongjak.setGeometry(QtCore.QRect(890, 700, 21, 31))
        self.Dongjak.setText("")
        self.Dongjak.setObjectName("Dongjak")
        self.Cityhall = QtWidgets.QLabel(self.centralwidget)
        self.Cityhall.setEnabled(True)
        self.Cityhall.setGeometry(QtCore.QRect(830, 420, 21, 31))
        self.Cityhall.setText("")
        self.Cityhall.setObjectName("Cityhall")
        self.Hapjeong = QtWidgets.QLabel(self.centralwidget)
        self.Hapjeong.setEnabled(True)
        self.Hapjeong.setGeometry(QtCore.QRect(680, 530, 20, 21))
        self.Hapjeong.setText("")
        self.Hapjeong.setObjectName("Hapjeong")
        self.Dangsan = QtWidgets.QLabel(self.centralwidget)
        self.Dangsan.setEnabled(True)
        self.Dangsan.setGeometry(QtCore.QRect(610, 540, 20, 21))
        self.Dangsan.setText("")
        self.Dangsan.setObjectName("Dangsan")
        self.Yeongdeungpoguoffice = QtWidgets.QLabel(self.centralwidget)
        self.Yeongdeungpoguoffice.setEnabled(True)
        self.Yeongdeungpoguoffice.setGeometry(QtCore.QRect(560, 550, 20, 21))
        self.Yeongdeungpoguoffice.setText("")
        self.Yeongdeungpoguoffice.setObjectName("Yeongdeungpoguoffice")
        self.Singil = QtWidgets.QLabel(self.centralwidget)
        self.Singil.setEnabled(True)
        self.Singil.setGeometry(QtCore.QRect(630, 610, 20, 21))
        self.Singil.setText("")
        self.Singil.setObjectName("Singil")
        self.Yeouido = QtWidgets.QLabel(self.centralwidget)
        self.Yeouido.setEnabled(True)
        self.Yeouido.setGeometry(QtCore.QRect(690, 610, 31, 31))
        self.Yeouido.setText("")
        self.Yeouido.setObjectName("Yeouido")
        self.Noryangjin = QtWidgets.QLabel(self.centralwidget)
        self.Noryangjin.setEnabled(True)
        self.Noryangjin.setGeometry(QtCore.QRect(750, 670, 20, 21))
        self.Noryangjin.setText("")
        self.Noryangjin.setObjectName("Noryangjin")
        self.Onsu = QtWidgets.QLabel(self.centralwidget)
        self.Onsu.setEnabled(True)
        self.Onsu.setGeometry(QtCore.QRect(460, 710, 20, 21))
        self.Onsu.setText("")
        self.Onsu.setObjectName("Onsu")
        self.Gasandigitalcomplex = QtWidgets.QLabel(self.centralwidget)
        self.Gasandigitalcomplex.setEnabled(True)
        self.Gasandigitalcomplex.setGeometry(QtCore.QRect(570, 750, 20, 31))
        self.Gasandigitalcomplex.setText("")
        self.Gasandigitalcomplex.setObjectName("Gasandigitalcomplex")
        self.Dongjak_2 = QtWidgets.QLabel(self.centralwidget)
        self.Dongjak_2.setEnabled(True)
        self.Dongjak_2.setGeometry(QtCore.QRect(890, 700, 20, 31))
        self.Dongjak_2.setText("")
        self.Dongjak_2.setObjectName("Dongjak_2")
        self.Chongshinuniv = QtWidgets.QLabel(self.centralwidget)
        self.Chongshinuniv.setEnabled(True)
        self.Chongshinuniv.setGeometry(QtCore.QRect(890, 750, 20, 21))
        self.Chongshinuniv.setText("")
        self.Chongshinuniv.setObjectName("Chongshinuniv")
        self.Sadang = QtWidgets.QLabel(self.centralwidget)
        self.Sadang.setEnabled(True)
        self.Sadang.setGeometry(QtCore.QRect(890, 800, 20, 21))
        self.Sadang.setText("")
        self.Sadang.setObjectName("Sadang")
        self.Kkachisan = QtWidgets.QLabel(self.centralwidget)
        self.Kkachisan.setEnabled(True)
        self.Kkachisan.setGeometry(QtCore.QRect(420, 550, 21, 21))
        self.Kkachisan.setText("")
        self.Kkachisan.setObjectName("Kkachisan")
        self.GimpoAirport = QtWidgets.QLabel(self.centralwidget)
        self.GimpoAirport.setEnabled(True)
        self.GimpoAirport.setGeometry(QtCore.QRect(310, 430, 21, 21))
        self.GimpoAirport.setText("")
        self.GimpoAirport.setObjectName("GimpoAirport")
        self.Jongno3ga = QtWidgets.QLabel(self.centralwidget)
        self.Jongno3ga.setEnabled(True)
        self.Jongno3ga.setGeometry(QtCore.QRect(900, 350, 21, 21))
        self.Jongno3ga.setText("")
        self.Jongno3ga.setObjectName("Jongno3ga")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1911, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Daehwa.setText(_translate("MainWindow", "   "))
        self.label.setText(_translate("MainWindow", "How many?"))
        self.people_group_1.setTitle(_translate("MainWindow", "1"))
        self.people_group_2.setTitle(_translate("MainWindow", "2"))
        self.people_group_3.setTitle(_translate("MainWindow", "3"))
        self.people_group_4.setTitle(_translate("MainWindow", "4"))
        self.run_button.setText(_translate("MainWindow", "RUN"))


import subway_map_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
